alias ka 'kubectl apply -f'
alias kd 'kubectl describe'
alias kdp 'kubectl describe pod'
alias kg 'kubectl get --show-kind'
alias ky 'kubectl get -oyaml'
alias kj 'kubectl get -ojson'
alias kgp 'kubectl get --show-kind pod'
alias kgs 'kubectl get --show-kind service'
alias kl 'kubectl logs --since 10m'
alias kla 'kubectl logs --since 10m --all-containers'
alias kns 'kubens'
alias ku 'kubectl'
alias kuctx 'kubectl config use-context'
alias kx 'kubectl exec -it'
